export default [
  {
    id: "ost1",
    text: "<h2><li>Common sense is indispensable!</li></h2>",
    startTime: 19.376324,
    endTime: 34.503294,
  },
  {
    id: "ost2",
    text: "<h2><li>First, we consider the Context of the data.</li></h2>",
    startTime: 34.503294,
    middleTime: 37.271896,
    transform: true,
    endTime: 62.03019,
  },
  {
    id: "ost3",
    text: "<li>Identify what the data represent.</li>",
    startTime: 37.271896,
    middleTime: 39.964833,
    transform: true,
    endTime: 62.03019,
  },
  {
    id: "ost4",
    text: "<li>Are the data the result of responses to a survey?</li>",
    startTime: 40.223164,
    middleTime: 43.695476,
    transform: true,
    endTime: 62.03019,
  },
  {
    id: "ost5",
    text:
      "<li>Are the data the result of measurements of weights of manufactured truck tires?</li>",
    startTime: 44.276194,
    middleTime: 48.647485,
    transform: true,
    endTime: 62.03019,
  },
  {
    id: "ost6",
    text: "<li>Were the data measured or were they reported by survey respondents?</li>",
    startTime: 48.995589,
    middleTime: 54.261726,
    transform: true,
    endTime: 62.03019,
  },
  {
    id: "ost7",
    text: '<li>All of these questions are typical of this general and important question: “What are we dealing with here?"</li>',
    startTime: 54.345054,
    middleTime: 61.64374,
    transform: true,
    endTime: 62.506145,
  },
  {
    id: "ost8",
    text: "<li>Also, identify the <em><strong>GOAL</strong></em> of the study.</li>",
    startTime: 62.863241,
    middleTime: 65.506145,
    transform: true,
    endTime: 94.069677,
  },
  {
    id: "ost9",
    text: "<li>Are you trying to establish that a new drug for lower blood pressure is effective?</li>",
    startTime: 65.870429,
    middleTime: 71.416917,
    transform: true,
    endTime: 94.069677,
  },
  {
    id: "ost10",
    text: "<li>Are you trying to establish that “most” adults text while they are driving?</li>",
    startTime: 71.702787,
    middleTime: 76.385473,
    transform: true,
    endTime: 94.069677,
  },
  {
    id: "ost11",
    text: "<li>Are you trying to establish that there is a correlation between drinking alcohol and the ability to text on smartphone?</li>",
    startTime: 76.980908,
    middleTime: 84.448173,
    transform: true,
    endTime: 94.069677,
  },
  {
    id: "ost12",
    text: "<li>The goal of the study can have a dramatic effect on the sample data to be collected and the statistical methods that are to be used.</li>",
    startTime: 84.993639,
    middleTime: 93.576243,
    transform: true,
    endTime: 94.069677,
  },
  {
    id: "ost",
    text: "<li>The next step in our preparation is to identify the source from which the data were obtained. Use critical thinking to determine whether the source is reliable so that the data are likely to lead to meaningful conclusions. </li>",
    startTime: 94.608018,
    middleTime: 110.137375,
    transform: true,
    endTime: 146.35433,
  },
  {
    id: "ost13",
    text: "<li>Be very critical of data obtained from a source that could somehow benefit from the results.</li>",
    startTime: 111.432939,
    middleTime: 117.043096,
    transform: true,
    endTime: 146.35433,
  },
  {
    id: "ost14",
    text:
      "<li>For example, be wary of data from a study of the beneficial health effects of candy when the study was sponsored by a manufacturer of candy.</li>",
    startTime: 117.777699,
    middleTime: 128.333279,
    transform: true,
    endTime: 146.35433,
  },
  {
    id: "ost15",
    text: "<li>As another example, several examples in your textbook will involve cases in which data are obtained in a procedure through which people decide themselves to participate in the study.</li>",
    startTime: 130.051034,
    middleTime: 142.062423,
    transform: true,
    endTime: 146.35433,
  },

  {
    id: "ost16",
    text: "<li>This relates to the next item of <em>sampling method</em>. </li>",
    startTime: 142.302947,
    middleTime: 146.235924,
    transform: true,
    endTime: 146.35433,
  },
  {
    id: "ost17",
    text: "<li>We conclude our preparation by considering the sampling method. Your textbook includes information on different sampling methods including random samples, convenience samples and systematic samples.</li>",
    startTime: 146.519609,
    middleTime: 160.765871,
    transform: true,
    endTime: 214.022728,
  },

  {
    id: "ost18",
    text: "<li>Many effective and meaningful statistical studies involve the method of <em>random sampling</em>.</li>",
    startTime: 161.69555,
    middleTime: 167.311528,
    transform: true,
    endTime: 214.022728,
  },
  {
    id: "ost19",
    text: "<li>For example, conduct a random sample of students attending your college by compiling a list of the names of all students, then using a method of randomly selecting 300 of them. The method of actually making the selection random must be carefully planned.</li>",
    startTime: 167.72558,
    middleTime: 186.981261,
    transform: true,
    endTime: 214.022728,
  },
  {
    id: "ost20",
    text: "<li>The random sampling must be equivalent to flipping a coin or rolling a die. </li>",
    startTime: 187.66260,
    middleTime: 193.506764,
    transform: true,
    endTime: 214.022728,
  },
  {
    id: "ost21",
    text: "<li>Also, it is essential to recognize that when respondents <em>volunteer</em> to participate, there could easily be a tendency to get results that are biased, and such volunteered data might well be totally worthless for any sound statistical analysis.</li>",
    startTime: 193.862064,
    middleTime: 213.668094,
    transform: true,
    endTime: 214.022728,
  },
  {
    id: "ost22",
    text: "<li>Examples of such voluntary participation include a survey published on a website with a request that readers respond online, or a survey mailed to potential respondents with a request to mail back their completed responses.</li>",
    startTime: 214.022728,
    middleTime: 230.588309,
    transform: true,
    endTime: 232.588309,
  },
  {
    id: "ost23",
    text: "<li>After completing our preparation, we begin to <em>Analyze</em> the data. Analysis begins with exploration of the data including creating appropriate graphs. Your textbook describes a variety of different graphs, and it will be important to select graphs that are relevant for the sample data.</li>",
    startTime: 234.855126,
    middleTime: 255.0256,
    transform: true,
    endTime: 278.936403,
  },

  {
    id: "ost24",
    text: "<li>But it is <em>always</em> wise to create a suitable graph that could be helpful in letting you see characteristics of the sample data.</li>",
    startTime: 255.04568,
    middleTime: 263.356829,
    transform: true,
    endTime: 278.936403,
  },
  {
    id: "ost25",
    text: "<li>Graphs may reveal that it might not be appropriate to use some statistical methods that you had been planning to use.</li>",
    startTime: 263.544083,
    middleTime: 271.687293,
    transform: true,
    endTime: 278.936403,
  },
  {
    id: "ost26",
    text: "<li>Much time can be saved by looking at the data before we leap into statistical analysis.</li>",
    startTime: 271.991426,
    middleTime: 278.248581,
    transform: true,
    endTime: 278.936403,
  },
  {
    id: "ost27_",
    text: "<li> Plot the data!</li>",
    startTime: 278.704382,
    middleTime: 281.240105,
    transform: true,
    endTime: 327.08643,
  },
  {
    id: "ost27__",
    text: "<li> Next, we explore the data.</li>",
    startTime: 281.240105,
    middleTime: 284.066608,
    transform: true,
    endTime: 327.08643,
  },
  {
    id: "ost27",
    text: "<li> A suitable graph might be helpful in letting you see that there are some data values that are far from almost all of the other data values.  </li>",
    startTime: 284.126096,
    middleTime: 292.804295,
    transform: true,
    endTime: 327.08643,
  },

  {
    id: "ost28",
    text: "<li> Such “outliers” can have a dramatic effect on results, so it is important to identify them at the outset.<span class='outliers-img'></span>  </li>",
    startTime: 293.073835,
    middleTime: 301.626988,
    transform: true,
    endTime: 327.08643,
  },
  {
    id: "ost28_",
    text: "<li> What important statistics summarize the data? The mean? The standard deviation?  </li>",
    startTime: 302.150896,
    middleTime: 310.232287,
    transform: true,
    endTime: 327.08643,
  },
  {
    id: "ost29",
    text: "<li> Explore the <em>distribution</em> of the data by using suitable graphs. Is the distribution bell-shaped or does it have some other shape? <span class='bell-shaped-img'> </span>  </li>",
    startTime: 310.514246,
    middleTime: 319.234024,
    transform: true,
    endTime: 327.08643,
  },
  {
    id: "ost30",
    text: "<li>  Are many data values missing? Are there many survey respondents who refused to cooperate?  </li>",
    startTime: 319.464999,
    middleTime: 326.297918,
    transform: true,
    endTime: 327.08643,
  },

  {
    id: "ost31",
    text: "<li>After exploring the data, we move to applying statistical methods in our analysis.</li>",
    startTime: 327.17469,
    middleTime: 333.070598,
    transform: true,
    endTime: 366.819146,
  },
  {
    id: "ost32",
    text: "<li>The selection of a particular statistical method should definitely follow the preceding considerations --- it should not be the first step in a statistical study.</li>",
    startTime: 333.326499,
    middleTime: 344.626429,
    transform: true,
    endTime: 366.819146,
  },
  {
    id: "ost33",
    text: "<li>In many cases, there could be a few different statistical methods that could be applied, and it would be wise to use all of those different methods instead of relying solely on one of them.</li>",
    startTime: 344.912078,
    middleTime: 358.745881,
    transform: true,
    endTime: 366.819146,
  },
  {
    id: "ost34",
    text: "<li>Use technology for the actual application of the statistical method.</li>",
    startTime: 359.150984,
    middleTime: 363.654426,
    transform: true,
    endTime: 366.819146,
  },
  {
    id: "ost35",
    text: "<li>After analyzing the data, the final step in our statistical process involves conclusions.</li>",
    startTime: 367.982688,
    middleTime: 375.22015,
    transform: true,
    endTime: 415.381083,
  },
  {
    id: "ost36",
    text: "<li><span class='sr-only'>In reaching conclusions, it is important to understand the difference between statistical significance and practical significance.</span> <span aria-hidden='true'>In reaching conclusions, it is important to understand the difference between <em>statistical significance</em> and <em>practical significance</em>.</span></li>",
    startTime: 376.361239,
    middleTime: 385.306682,
    transform: true,
    endTime: 415.381083,
  },
  {
    id: "ost37",
    text: "<li>For example, it might be that a large study shows that a diet pill has statistical significance, but if that treatment results in an average weight loss of only one pound after one year, it doesn’t have practical significance.</li>",
    startTime: 385.546934,
    middleTime: 403.853436,
    transform: true,
    endTime: 415.381083,
  },
  {
    id: "ost38",
    text: "<li>Again, common sense and critical thinking are essential tools for the effective use of statistical methods.</li>",
    startTime: 404.15235,
    middleTime: 411.94592,
    transform: true,
    endTime: 415.381083,
  },
  {
    id: "ost39",
    text: "<li>In summary, this flowchart presents the key elements to be used for statistical thinking and critical thinking. </li>",
    startTime: 415.704211,
    middleTime: 415.704211,
    transform: true,
    endTime: 440.022867,
    // chartHidden: true
  },
  {
    id: "ost40",
    text: "<li>Remember, it’s important to constantly use common sense and do not become blinded by mindlessly jumping into an application of some statistical method.</li>",
    startTime: 424.344801,
    middleTime: 424.344801,
    transform: true,
    endTime: 440.022867,
    // chartHidden: true
  },

];
