export default [
  {
    id: "cc0",
    startTime: 0.10,
    endTime: 8.395033,
    text: "The goal of this activity is to understand the process for finding the P-value in a hypothesis test."
  },
  {
    id: "cc1",
    startTime: 8.395033,
    endTime: 14.382927,
    text: "<span class='sr-only'>Before working with this flowchart, we should already know the definition of a P-value.</span><span aria-hidden='true' >Before working with this flowchart, we should already know the definition of a <q>P-value.</q></span>",
  },
  {
    id: "cc2",
    startTime: 14.382927,
    endTime: 16.244216,
    text: "In a hypothesis test,",
  },
  {
    id: "cc2",
    startTime: 16.244216,
    endTime: 20.964538,
    text: "<span class='sr-only'>the P-value is the probability of getting a value of the test statistic</span><span aria-hidden='true'>the <em>P</em>-value is the probability of getting a value of the test statistic</span>",
  },
  {
    id: "cc2",
    startTime: 20.964538,
    endTime: 27.817968,
    text: "<span class='sr-only'>that is at least as extreme as the test statistic obtained from the sample data,</span><span aria-hidden='true'>that is <em>at least as extreme</em> as the test statistic obtained from the sample data,</span>",
  },
  {
    id: "cc2",
    startTime: 27.817968,
    endTime: 30.799394,
    text: "assuming that the null hypothesis is true.",
  },
  {
    id: "cc3",
    startTime: 30.799394,
    endTime: 34.009537,
    text:"Also, before working with this flowchart,",
  },
  {
    id: "cc4",
    startTime: 34.009537,
    endTime: 41.976647,
    text: "<span class='sr-only'>we should be able to determine whether a particular hypothesis test is two-tailed, left-tailed, or right tailed.</span><span aria-hidden='true'>we should be able to determine whether a particular hypothesis test is two-tailed, left-tailed, or right tailed.</span>",
  },
  {
    id: "cc5",
    startTime: 41.976647,
    endTime: 50.328218,
    text: "<span class='sr-only'>For a Two-tailed test: The critical region is in the two extreme regions (or tails) under the curve.</span><span aria-hidden='true'>For a Two-tailed test: The critical region is in the two extreme regions (or tails) under the curve.</span>",
  },
  {
    id: "cc6",
    startTime: 50.328218,
    endTime: 57.617345,
    text: "<span class='sr-only'>For a Left-tailed test: The critical region is in the extreme left region (or tail) under the curve.</span><span aria-hidden='true'>For a Left-tailed test: The critical region is in the extreme left region (or tail) under the curve.</span>",
  },
  {
    id: "cc7",
    startTime: 57.617345,
    endTime: 66.125847,
    text: "<span class='sr-only'>For a Right-tailed test: The critical region is in the extreme right region (or tail) under the curve.</span><span aria-hidden='true'>For a Right-tailed test: The critical region is in the extreme right region (or tail) under the curve.</span>",
  },
  {
    id: "cc8",
    startTime: 66.125847,
    endTime: 69.970579,
    text: "<span class='sr-only'>It’s time to test your knowledge.</span><span aria-hidden='true'>It’s time to test your knowledge.</span>",
  },
  {
    id: "cc9",
    startTime: 70.970579,
    endTime: 73.27691,
    text: "Click on the Start button.",
  },
  {
    id: "cc10",
    startTime: 73.87691,
    endTime: 77.837301,
    text: "The first step is to identify what type of test it is.",
  },
  {
    id: "cc11",
    startTime: 77.837301,
    endTime: 85.148115,
    text: "<span class='sr-only'>Is it a two-tailed test, left-tailed test, or right-tailed test?</span><span aria-hidden='true'>Is it a two-tailed test, left-tailed test, or right-tailed test?</span>",
  },
  {
    id: "cc12",
    startTime: 85.148115,
    endTime: 88.461168,
    text: "Let’s consider a particular example.",
  },
  {
    id: "cc13",
    startTime: 88.471168,
    endTime: 99.256088,
    text: "IQ tests are designed so that the general population has a mean IQ score of 100. So the population mean is 100.",
  },
  {
    id: "cc14",
    startTime: 99.266088,
    endTime: 106.119725,
    text: "Suppose a random sample of statistics students has a mean IQ score of 120.",
  },
  {
    id: "cc15",
    startTime: 106.119725,
    endTime: 108.157712,
    text: "Based on that sample,",
  },
  {
    id: "cc15",
    startTime: 108.157712,
    endTime: 114.287998,
    text: "<span class='sr-only'>we make the claim that the “statistics students have a mean IQ score that is GREATER THAN 100.”</span><span aria-hidden='true'>we make the claim that the <q>statistics students have a mean IQ score that is <em>GREATER THAN</em> 100.</q></span>",
  },
  {
    id: "cc15",
    startTime: 114.287998,
    endTime: 123.65516,
    text: "<span class='sr-only'>Does that claim correspond to a hypothesis test that is two-tailed, left-tailed, or right-tailed?</span><span aria-hidden='true'>Does that claim correspond to a hypothesis test that is two-tailed, left-tailed, or right-tailed?</span>",
  },
  {
    id: "cc16",
    startTime: 124.87516,
    endTime: 126.251748,
    text: "<span class='sr-only'>That is incorrect.</span><span aria-hidden='true'>That is incorrect.</span>",
  },
  {
    id: "cc17",
    startTime: 126.251748,
    endTime: 132.42035,
    text: "<span class='sr-only'>The claim is that statistics students have a mean IQ score that is GREATER THAN 100,</span><span aria-hidden='true'>The claim is that statistics students have a mean IQ score that is <em>GREATER THAN</em> 100,</span>",
  },
  {
    id: "cc17",
    startTime: 132.42035,
    endTime: 140.250255,
    text: "<span class='sr-only'>so the alternative hypothesis is that the mean IQ score of statistics students is GREATER THAN 100.</span><span aria-hidden='true'>so the alternative hypothesis is that the mean IQ score of statistics students is <em>GREATER THAN</em> 100.</span>",
  },
  {
    id: "cc17",
    startTime: 140.250255,
    endTime: 144.682001,
    text: "<span class='sr-only'>The critical region is in the RIGHT tail of the distribution.</span><span aria-hidden='true'>The critical region is in the <em>RIGHT</em> tail of the distribution.</span>",
  },
  {
    id: "cc18",
    startTime: 144.682001,
    endTime: 146.794119,
    text: "Please try again.",
  },
  {
    id: "cc19",
    startTime: 148.329119,
    endTime: 149.601711,
    text: "<span class='sr-only'>Correct!</span><span aria-hidden='true'>Correct!</span>",
  },
  {
    id: "cc20",
    startTime: 149.601711,
    endTime: 154.979224,
    text: "The test is right-tailed because the critical region is located to the right.",
  },
  {
    id: "cc20",
    startTime: 154.979224,
    endTime: 159.4292,
    text: "Only a sample mean greater than 100 by a significant amount",
  },
  {
    id: "cc20",
    startTime: 159.4292,
    endTime: 166.324126,
    text: "would support the given claim that statistics students have a mean IQ score that is greater than 100.",
  },
  {
    id: "cc21",
    startTime: 166.324126,
    endTime: 173.165043,
    text: "<span class='sr-only'>For this right-tailed test, the P-value is the area to the RIGHT of the test statistic.</span><span aria-hidden='true'>For this right-tailed test, the <em>P</em>-value is the area to the <em>RIGHT</em> of the test statistic.</span>",
  },
  {
    id: "cc22",
    startTime: 173.165043,
    endTime: 176.64217,
    text: "<span class='sr-only'>Now let’s consider a different example.</span><span aria-hidden='true'>Now let’s consider a different example.</span>",
  },
  {
    id: "cc23",
    startTime: 176.64217,
    endTime: 182.920526,
    text: "<span class='sr-only'>Suppose a random sample of professional wrestlers has a mean IQ score of 98.</span><span aria-hidden='true'>Suppose a random sample of <em>professional wrestlers</em> has a mean IQ score of 98.</span>",
  },
  {
    id: "cc24",
    startTime: 182.920526,
    endTime: 184.393911,
    text: "Based on that sample,",
  },
  {
    id: "cc24",
    startTime: 184.393911,
    endTime: 191.279308,
    text: "<span class='sr-only'>we make the claim that “professional wrestlers have a mean IQ score that is LESS THAN 100.”</span><span aria-hidden='true'>we make the claim that <q>professional wrestlers have a mean IQ score that is <em>LESS THAN</em> 100.</q></span>",
  },
  {
    id: "cc25",
    startTime: 191.279308,
    endTime: 200.282233,
    text: "<span class='sr-only'>Does that claim correspond to a hypothesis test that is two-tailed, left-tailed, or right-tailed?</span><span aria-hidden='true'>Does that claim correspond to a hypothesis test that is two-tailed, left-tailed, or right-tailed?</span>",
  },
  {
    id: "cc26",
    startTime: 201.682233,
    endTime: 203.270794,
    text: "<span class='sr-only'>That is incorrect.</span><span aria-hidden='true'>That is incorrect.</span>",
  },
  {
    id: "cc27",
    startTime: 203.270794,
    endTime: 208.786075,
    text: "<span class='sr-only'>The claim is that wrestlers have a mean IQ score that is LESS THAN 100,</span><span aria-hidden='true'>The claim is that wrestlers have a mean IQ score that is <em>LESS THAN</em> 100,</span>",
  },
  {
    id: "cc27",
    startTime: 208.786075,
    endTime: 216.116115,
    text: "<span class='sr-only'>so the alternative hypothesis is that the mean IQ score of wrestlers is LESS THAN 100</span><span aria-hidden='true'>so the alternative hypothesis is that the mean IQ score of wrestlers is <em>LESS THAN</em> 100</span>",
  },
  {
    id: "cc27",
    startTime: 216.116115,
    endTime: 220.569936,
    text: "<span class='sr-only'>and the critical region is in the LEFT tail of the distribution.</span><span aria-hidden='true'>and the critical region is in the <em>LEFT</em> tail of the distribution.</span>",
  },
  {
    id: "cc28",
    startTime: 220.569936,
    endTime: 222.479314,
    text: "Please try again.",
  },
  {
    id: "cc29",
    startTime: 223.379314,
    endTime: 224.007149,
    text: "<span class='sr-only'>Correct!</span><span aria-hidden='true'>Correct!</span>",
  },
  {
    id: "cc30",
    startTime: 224.007149,
    endTime: 228.663479,
    text: "The test is left-tailed because the critical region is located to the left.",
  },
  {
    id: "cc30",
    startTime: 228.663479,
    endTime: 235.40223,
    text: "Only a sample mean less than 100 by a significant amount would support the given claim",
  },
  {
    id: "cc30",
    startTime: 235.40223,
    endTime: 241.076986,
    text: "that the professional wrestlers have a mean IQ score that is less than 100.",
  },
  {
    id: "cc31",
    startTime: 241.076986,
    endTime: 248.252257,
    text: "<span class='sr-only'>For this left-tailed test, the P-value is the area to the LEFT of the test statistic.</span><span aria-hidden='true'>For this left-tailed test, the <em>P</em>-value is the area to the <em>LEFT</em> of the test statistic.</span>",
  },
  {
    id: "cc32",
    startTime: 248.252257,
    endTime: 250.611348,
    text: "<span class='sr-only'>It’s time to test your knowledge.</span><span aria-hidden='true'>It’s time to test your knowledge.</span>",
  },
  {
    id: "cc33",
    startTime: 251.311348,
    endTime: 252.96651,
    text: "Let’s look at a third example",
  },
  {
    id: "cc33",
    startTime: 252.96651,
    endTime: 259.62827,
    text: "<span class='sr-only'>and again suppose that a random sample of statistics students has a mean IQ score of 120.</span><span aria-hidden='true'>and again suppose that a random sample of <em>statistics students</em> has a mean IQ score of 120.</span>",
  },
  {
    id: "cc34",
    startTime: 259.62827,
    endTime: 261.77601,
    text: "Based on that sample,",
  },
  {
    id: "cc34",
    startTime: 261.77601,
    endTime: 268.3372,
    text: "<span class='sr-only'>we make the claim that “statistics students have a mean IQ score that is DIFFERENT THAN 100.”</span><span aria-hidden='true'>we make the claim that “statistics students have a mean IQ score that is <em>DIFFERENT THAN</em> 100.”</span",
  },
  {
    id: "cc35",
    startTime: 268.3372,
    endTime: 276.786627,
    text: "<span class='sr-only'>Does that claim correspond to a hypothesis test that is two-tailed, left-tailed, or right-tailed?</span><span aria-hidden='true'>Does that claim correspond to a hypothesis test that is two-tailed, left-tailed, or right-tailed?</span>",
  },
  {
    id: "cc36",
    startTime: 277.996627,
    endTime: 279.692905,
    text: "<span class='sr-only'>That is incorrect.</span><span aria-hidden='true'>That is incorrect.</span>",
  },
  {
    id: "cc37",
    startTime: 279.692905,
    endTime: 285.293093,
    text: "<span class='sr-only'>The claim is that statistics students have a mean IQ score that is DIFFERENT THAN 100,</span><span aria-hidden='true'>The claim is that statistics students have a mean IQ score that is <em>DIFFERENT THAN</em> 100,</span>",
  },
  {
    id: "cc37",
    startTime: 285.293093,
    endTime: 293.021044,
    text: "<span class='sr-only'>so the alternative hypothesis is that the mean IQ score of statistics students is NOT EQUAL TO 100.</span><span aria-hidden='true'>so the alternative hypothesis is that the mean IQ score of statistics students is <em>NOT EQUAL TO</em> 100.</span>",
  },
  {
    id: "cc37",
    startTime: 293.021044,
    endTime: 300.383772,
    text: "<span class='sr-only'>The critical region is in BOTH the LEFT TAIL and the RIGHT Tail of the distribution.</span><span aria-hidden='true'>The critical region is in <em>BOTH</em> the <em>LEFT TAIL</em> and the <em>RIGHT Tail</em> of the distribution.</span>",
  },
  {
    id: "cc38",
    startTime: 300.383772,
    endTime: 302.21966,
    text: "Please try again.",
  },
  {
    id: "cc39",
    startTime: 302.99966,
    endTime: 303.660262,
    text: "<span class='sr-only'>Correct!</span><span aria-hidden='true'>Correct!</span>",
  },
  {
    id: "cc40",
    startTime: 303.660262,
    endTime: 309.965837,
    text: "The test is two-tailed because the critical region is located to the right and to the left.",
  },
  {
    id: "cc40",
    startTime: 309.965837,
    endTime: 318.759824,
    text: "Only a sample mean less than 100 by a significant amount or greater than 100 by a significant amount",
  },
  {
    id: "cc40",
    startTime: 318.759824,
    endTime: 325.889455,
    text: "would support the given claim that statistics students have a mean IQ score that is different than 100.",
  },
  {
    id: "cc41",
    startTime: 325.899455,
    endTime: 330.297793,
    text: "Now let’s consider the two possible cases for this two-tailed test.",
  },
  {
    id: "cc41",
    startTime: 330.297793,
    endTime: 337.272436,
    text: "The two possible cases involve (1) the test statistic is to the right of center",
  },
  {
    id: "cc41",
    startTime: 337.272436,
    endTime: 341.828844,
    text: "and (2) the test statistic is to the left of center.",
  },
  {
    id: "cc42",
    startTime: 341.828844,
    endTime: 350.499075,
    text: "First let’s continue with the example in which a random sample of statistics students has a mean IQ score of 120",
  },
  {
    id: "cc42",
    startTime: 350.499075,
    endTime: 357.575587,
    text: "<span class='sr-only'>and we are testing the claim that “statistics students have a mean IQ score DIFFERENT THAN 100.”</span><span aria-hidden='true'>and we are testing the claim that <q>statistics students have a mean IQ score DIFFERENT THAN 100.</q></span>",
  },
  {
    id: "cc43",
    startTime: 357.575587,
    endTime: 366.436643,
    text: "Using technology, the area to the right of the corresponding test statistic is found to be 0.03.",
  },
  {
    id: "cc43",
    startTime: 366.436643,
    endTime: 369.518229,
    text: "<span class='sr-only'>What is the P-value for this two-tailed test?</span><span aria-hidden='true'>What is the <em>P</em>-value for this two-tailed test?</span>",
  },
  {
    id: "cc44",
    startTime: 369.518229,
    endTime: 375.875828,
    text: "<span class='sr-only'>For a two-tailed test, the P-value is TWICE the area beyond the test statistic.</span><span aria-hidden='true'>For a two-tailed test, the <em>P</em>-value is <em>TWICE</em> the area beyond the test statistic.</span>",
  },
  {
    id: "cc45",
    startTime: 375.875828,
    endTime: 380.147753,
    text: "<span class='sr-only'>In this case, the P-value is equal to 0.06.</span><span aria-hidden='true'>In this case, the <em>P<em>-value is equal to 0.06.</span>",
  },
  {
    id: "cc46",
    startTime: 380.147753,
    endTime: 388.163498,
    text: "<span class='sr-only'>Second let’s consider a different example in which a random sample of statistics students has a mean IQ score of 98</span><span aria-hidden='true'>Second let’s consider a different example in which a random sample of statistics students has a mean IQ score of <em>98</em></span>",
  },
  {
    id: "cc46",
    startTime: 388.163498,
    endTime: 394.419718,
    text: "<span class='sr-only'>and we are testing the claim that the “statistics students have a mean IQ score DIFFERENT THAN 100.”</span><span aria-hidden='true'>and we are testing the claim that the <q>statistics students have a mean IQ score DIFFERENT THAN 100.</q></span>",
  },
  {
    id: "cc47",
    startTime: 394.419718,
    endTime: 402.033766,
    text: "<span class='sr-only'>Using technology, the area to the LEFT of the corresponding test statistic is found to be 0.03.</span><span aria-hidden='true'>Using technology, the area to the <em>LEFT</em> of the corresponding test statistic is found to be 0.03.</span>",
  },
  {
    id: "cc47",
    startTime: 402.033766,
    endTime: 405.277064,
    text: "<span class='sr-only'>What is the P-value for this two-tailed test?</span><span aria-hidden='true'>What is the <em>P</em>-value for this two-tailed test?</span>",
  },
  {
    id: "cc48",
    startTime: 405.277064,
    endTime: 411.273456,
    text: "<span class='sr-only'>For a two-tailed test, the P-value is TWICE the area beyond the test statistic.</span><span aria-hidden='true'>For a two-tailed test, the <em>P<em>-value is <em>TWICE</em> the area beyond the test statistic.</span>",
  },
  {
    id: "cc49",
    startTime: 411.273456,
    endTime: 415.877746,
    text: "<span class='sr-only'>In this case, the P-value is equal to 0.06.</span><span aria-hidden='true'>In this case, the <em>P</em>-value is equal to 0.06.</span>",
  },
  {
    id: "cc50",
    startTime: 416.397746,
    endTime: 422.256579,
    text: "<span class='sr-only'>In both of these two possible cases, the P-value is equal to 0.06,</span><span aria-hidden='true'>In both of these two possible cases, the <em>P</em>-value is equal to 0.06,</span>",
  },
  {
    id: "cc50",
    startTime: 422.256579,
    endTime: 426.16276,
    text: "<span class='sr-only'>which is TWICE the area beyond the test statistic.</span><span aria-hidden='true'>which is <em>TWICE</em> the area beyond the test statistic.</span>",
  },
  {
    id: "cc51",
    startTime: 427.94276,
    endTime: 429.986767,
    text: "<span class='sr-only'>It’s time to test your knowledge.</span><span aria-hidden='true'>It’s time to test your knowledge.</span>",
  },
  {
    id: "cc52",
    startTime: 430.986767,
    endTime: 437.666412,
    text: "<span class='sr-only'>In summary, the p-value in a left-tailed test is the area to the left of the test statistic,</span><span aria-hidden='true'>In summary, the p-value in a left-tailed test is the area to the left of the test statistic,</span>",
  },
  {
    id: "cc52",
    startTime: 437.666412,
    endTime: 443.638866,
    text: "<span class='sr-only'>the p-value in the right-tailed test is the area to the right of the test statistic,</span><span aria-hidden='true'>the p-value in the right-tailed test is the area to the right of the test statistic,</span>",
  },
  {
    id: "cc52",
    startTime: 443.638866,
    endTime: 450.915763,
    text: "<span class='sr-only'>but the p-value in a two-tailed test is twice the area in the tail.</span><span aria-hidden='true'>but the p-value in a two-tailed test is twice the area in the tail.</span>",
  },
  {
    id: "cc53",
    startTime: 452.571289,
    endTime: 458.267947,
    text: "Congratulations! You have mastered and important concept of Statistics.",
  },
  {
    id: "cc53",
    startTime: 458.267947,
    endTime: 464.277778,
    text: " We are now having more fun than human beings are normally allowed to have!",
  },
];
